# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gee-to-rasterio-tutorial',
                'doc_host': 'https://VehpuS.github.io',
                'git_url': 'https://github.com/VehpuS/gee-to-rasterio-tutorial',
                'lib_path': 'gee_to_rasterio_tutorial'},
  'syms': {}}